# Site settings
title:       Site DOM
email:       dom@domdiagnosticos.com.br
description: "Site sobre Estratégias de Recursos Humanos (RH)."
baseurl:     ""
url:         "http://www.dombrasil.net.br"

# Build settings
markdown:    kramdown
permalink:   pretty
